// PROJECT_SPEC.md §4.1 — "stable IDs for every experience, bullet, project,
// skill, education entry, certification and publication." Every id in the
// app is generated by code, one way, from here — never by the model.
export function createId(): string {
  return crypto.randomUUID();
}
